/* A Game of Hierarchies
 * Add POI 
 */

/*
Copyright (c) 2017 Markus Ehrenmüller-Jensen

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

use GoT;
GO

exec dbo.AddPOI 'Winterfell', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Bear Island', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Castle Cerwyn', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Deepwood Motte', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Dreadfort', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Greywater Watch', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Hornwood', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Karhold', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Last Hearth', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Torrhen''s Square', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'White Harbor', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Flint''s Finger', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Moat Cailin', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Barrowton', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Oldcastle', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Ramsgate', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Widow''s Watch', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Ironrath', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Highpoint', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Rillwater Crossing', 'The North', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Eyrie', 'The Vale of Arryn', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Bloody Gate', 'The Vale of Arryn', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Runestone', 'The Vale of Arryn', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Baelish Keep', 'The Vale of Arryn', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Redfort', 'The Vale of Arryn', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Riverrun', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Harrenhal', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Raventree Hall', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Seagard', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Stone Hedge', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Twins', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Pinkmaiden', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Acorn Hall', 'The Riverlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Casterly Rock', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Ashemark', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Crag', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Golden Tooth', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Lannisport', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Clegan''s Keep', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Crakehall', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Cornfield', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Banefort', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Deep Den', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Silverhall', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Hornvale', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Sarsfield', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Feastfires', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Faircastle', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Oxcross', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Castamere', 'The Westerlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Pyke', 'Iron Islands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Lordsport', 'Iron Islands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Ten Towers', 'Iron Islands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Red Harbor', 'Iron Islands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'King''s Landing', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Red Keep', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Duskendale', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Rosby', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Castle Stokeworth', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Antlers', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Sow''s Horn', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Rook''s Rest', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Whispers', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Dragonstone', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Sharp Point', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Stonedance', 'The Crownlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Storm''s End', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Haystack Hall', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Bronzegate', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Felwood', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Evenfall Hall', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Rain House', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Mistwood', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Stonehelm', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Griffin''s Roost', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Nightsong', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Blackhaven', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Crow''s Nest', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Summerhall', 'The Stormlands', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Highgarden', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Oldtown', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Brightwater Keep', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Bitterbridge', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Grassy Vale', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Long Table', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Cider Hall', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Goldengrove', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Red Lake', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Old Oak', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Horn Hill', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Uplands', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Honeyholt', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Sun House', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Three Towers', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Blackcrown', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Bandallon', 'The Reach', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Sunspear', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Planky Town', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Blackmont', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Starfall', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Kingsgrave', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Vulture''s Roost', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Wyl', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Yronwood', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Sandstone', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Hellholt', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Tor', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Vaith', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Godsgrace', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Saltshore', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Lemonwood', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Ghost Hill', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Water Gardens', 'Dorne', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Haunted Forest', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Fist of the First Man', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Frostfangs', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Milkwater', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Lands of Always Winter', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Frozen Shore', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Storrold''s Point', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Valley of the Thenn', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The Cave of the three-eyed raven', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Hardhome', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'The North Grove', 'Beyond the Wall', 'Westeros', 'The Known World'
exec dbo.AddPOI 'Braavos', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Lorath', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Lys', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Myr', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Norvos', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Pentos', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Qohor', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Tyrosh', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'Volantis', 'The Free Cities', 'Essos', 'The Known World'
exec dbo.AddPOI 'The Rhoyne River', 'The Rhoyne River', 'Essos', 'The Known World'
exec dbo.AddPOI 'Valyrian Peninsula', 'Valyrian Peninsula', 'Essos', 'The Known World'
exec dbo.AddPOI 'Meereen', 'Bay of Dragons', 'Essos', 'The Known World'
exec dbo.AddPOI 'Yunkai', 'Bay of Dragons', 'Essos', 'The Known World'
exec dbo.AddPOI 'Astapor', 'Bay of Dragons', 'Essos', 'The Known World'
exec dbo.AddPOI 'Vaes Dothrak', 'Dothraki Sea', 'Essos', 'The Known World'
exec dbo.AddPOI 'Shahadazhan', 'Lhazar', 'Essos', 'The Known World'
exec dbo.AddPOI 'The Red Waste', 'The Red Waste', 'Essos', 'The Known World'
exec dbo.AddPOI 'Qarth', 'Qarth', 'Essos', 'The Known World'
exec dbo.AddPOI 'Asshai', 'Asshai, the Jade Sea, and lands of the far east', 'Essos', 'The Known World'
exec dbo.AddPOI 'Yi Ti', 'Asshai, the Jade Sea, and lands of the far east', 'Essos', 'The Known World'
exec dbo.AddPOI 'Shadow Lands', 'Asshai, the Jade Sea, and lands of the far east', 'Essos', 'The Known World'
exec dbo.AddPOI 'Ibben', 'Asshai, the Jade Sea, and lands of the far east', 'Essos', 'The Known World'
exec dbo.AddPOI 'Summer Islands', 'Summer Islands', 'Sothoryos', 'The Known World'
exec dbo.AddPOI 'Naath', 'Summer Islands', 'Sothoryos', 'The Known World'

GO
